package ac.cult.cultac.network.packet;

import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.PacketType;
import net.minecraft.network.protocol.PacketUtils;
import net.minecraft.network.protocol.game.ServerGamePacketListener;
import net.minecraft.network.protocol.game.ServerboundMovePlayerPacket;
import net.minecraft.server.network.ServerGamePacketListenerImpl;

import java.lang.reflect.Field;

/** The server-side position update generated by Cult's setback, never a client packet. */
public final class ServerSetbackPosition {
    private static final Field RECEIVED_POSITION = findPositionCounter();

    private ServerSetbackPosition() {}

    public static Packet<?> wrap(ServerboundMovePlayerPacket position) {
        return RECEIVED_POSITION == null ? position : new TrustedPosition(position);
    }

    private static Field findPositionCounter() {
        try {
            Field field = Class.forName("net.minecraft.server.network.ServerGamePacketListenerImpl")
                    .getDeclaredField("receivedPositionThisTick");
            field.setAccessible(true);
            return field;
        } catch (ClassNotFoundException | NoSuchFieldException ignored) {
            return null;
        }
    }

    private record TrustedPosition(ServerboundMovePlayerPacket position) implements Packet<ServerGamePacketListener> {
        @Override
        public PacketType<? extends Packet<ServerGamePacketListener>> type() {
            return position.type();
        }

        @Override
        public void handle(ServerGamePacketListener listener) {
            var game = (ServerGamePacketListenerImpl) listener;
            // sending two movement packets without tick end between kicks the player on 26.3+
            // hopefully via can fix this without sending arbitrary tick ends which plugins
            // should never do...
            PacketUtils.ensureRunningOnSameThread(this, listener, game.player.level());
            try {
                boolean received = RECEIVED_POSITION.getBoolean(listener);
                RECEIVED_POSITION.setBoolean(listener, false);
                try {
                    position.handle(listener);
                } finally {
                    RECEIVED_POSITION.setBoolean(listener, received);
                }
            } catch (IllegalAccessException exception) {
                throw new IllegalStateException("Cannot apply the internal setback position", exception);
            }
        }
    }
}
